### ISSUE TITLE
Fix problems for fakebold in songti（实现宋体伪加粗）

### ISSUE THREAD

**Issue by VealM** [VealM/LZUthesis2020#4]
# 如何修正宋体加粗

## 问题描述：
在缺乏相应字体包的情况下，使用\beseries \songti不能正确加粗宋体(因为word的宋体加粗是伪加粗)，**因此目前未对封面页的 论文标题(中文) 论文标题(英文)进行加粗！！！** 与学校官方word文档封面页的对应部分有所差距。尝试使用\textbf， 则加粗效果为黑体。

## 可能的解决方案
1. 使用fandol
具体解决方案可参考ucas中科院大佬给出的[建议](https://github.com/mohuangrui/ucasthesis/issues/23) 但限于本咸鱼才疏学浅，暂时未能有效应用于LZUthesis。希望有大佬能在此帖下给出方案！
2. 暴力修改
进入兰大个人工作台-->应用市场-->更多应用-->福昕高级阅读器 下载后编辑pdf或转为word进行加粗（

**Comment by yuhldr** [comment]
伪加粗可以参考我的这个，把伪加粗放在tex文件开头，并且使用\bfseries \songti
[伪加粗](https://github.com/yuhlzu/LZUThesis2020/#%E7%8E%B0%E7%8A%B60%E4%BB%A5%E5%89%8D%E7%94%A8%E7%9A%84%E8%BF%99%E4%B8%AA%E6%A8%A1%E6%9D%BF%E7%8E%B0%E5%9C%A8%E9%9C%80%E8%A6%81%E5%8D%87%E7%BA%A7)

**Comment by VealM** [comment]
> 伪加粗可以参考我的这个，把伪加粗放在tex文件开头，并且使用\bfseries \songti
> [伪加粗](https://github.com/yuhlzu/LZUThesis2020/#%E7%8E%B0%E7%8A%B60%E4%BB%A5%E5%89%8D%E7%94%A8%E7%9A%84%E8%BF%99%E4%B8%AA%E6%A8%A1%E6%9D%BF%E7%8E%B0%E5%9C%A8%E9%9C%80%E8%A6%81%E5%8D%87%E7%BA%A7)

是这样的，感谢大佬~（昨天才发现你的repo，等我论文写清醒了认真看下你的配置文件
